export const FETCH_USER_POSTS_RESPOND = 'FETCH_USER_POSTS_RESPOND';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_FAILURE = 'FETCH_USER_POSTS_FAILURE';

export const FETCH_ALL_POSTS_RESPOND = 'FETCH_ALL_POSTS_RESPOND';
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_FAILURE = 'FETCH_ALL_POSTS_FAILURE';

export const ADD_POST = 'ADD_POST';

export const ADD_PLUS_RESPOND = 'ADD_PLUS_RESPOND';
export const ADD_PLUS_SUCCESS = 'ADD_PLUS_SUCCESS';
export const ADD_PLUS_FAILURE = 'ADD_PLUS_FAILURE';

export const ADD_MINUS_RESPOND = 'ADD_MINUS_RESPOND';
export const ADD_MINUS_SUCCESS = 'ADD_MINUS_SUCCESS';
export const ADD_MINUS_FAILURE = 'ADD_MINUS_FAILURE';

export const SET_USER_IS_SIGNED_IN = 'SET_USER_IS_SIGNED_IN';
export const SET_USER_IS_SIGNED_OUT = 'SET_USER_IS_SIGNED_OUT';
