export const FETCH_USER_POSTS_REQUEST = 'FETCH_USER_POSTS_REQUEST';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_FAILURE = 'FETCH_USER_POSTS_FAILURE';

export const FETCH_ALL_POSTS_REQUEST = 'FETCH_ALL_POSTS_REQUEST';
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_FAILURE = 'FETCH_ALL_POSTS_FAILURE';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const ADD_PLUS_REQUEST = 'ADD_PLUS_REQUEST';
export const ADD_PLUS_SUCCESS = 'ADD_PLUS_SUCCESS';
export const ADD_PLUS_FAILURE = 'ADD_PLUS_FAILURE';

export const ADD_MINUS_REQUEST = 'ADD_MINUS_REQUEST';
export const ADD_MINUS_SUCCESS = 'ADD_MINUS_SUCCESS';
export const ADD_MINUS_FAILURE = 'ADD_MINUS_FAILURE';

export const SET_USER_IS_SIGNED_IN = 'SET_USER_IS_SIGNED_IN';
export const SET_USER_IS_SIGNED_OUT = 'SET_USER_IS_SIGNED_OUT';

export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';
